# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/TestNBDEV',
                'doc_host': 'https://nathanhubens.github.io',
                'git_url': 'https://github.com/nathanhubens/TestNBDEV',
                'lib_path': 'TestNBDEV'},
  'syms': {'TestNBDEV.core': {'TestNBDEV.core.foo': ('core.html#foo', 'TestNBDEV/core.py')}}}
